dist: xenial
language: python
python:
  - 3.7
install:
  - pip install -r requirements/dev.txt
before_script:
  - export FLASK_ENV=development
  - black --check --diff .
  - flake8 .
  - mypy --strict flaskapp/
script: pytest
